/**
 * generate_pptx.js
 * Called by FastAPI: node generate_pptx.js '<json_string>' output.pptx
 *
 * Input JSON: { title: string, slides: [ { heading, bullets: string[], note } ] }
 */

const pptxgen = require("pptxgenjs");
const fs = require("fs");

const input = JSON.parse(process.argv[2]);
const outputPath = process.argv[3] || "output.pptx";

// ── Color palette: Midnight Executive (cybersecurity feel) ──────────────────
const DARK_BG   = "1E2761";   // navy — title & section slides
const LIGHT_BG  = "F7F9FC";   // near-white — content slides
const ACCENT    = "4FC3F7";   // sky blue — headings on dark
const BODY_COL  = "1E2761";   // navy — body text on light
const MUTED     = "64748B";   // slate — secondary text
const WHITE     = "FFFFFF";

const pres = new pptxgen();
pres.layout = "LAYOUT_16x9";
pres.title  = input.title;

// ── TITLE SLIDE ─────────────────────────────────────────────────────────────
const titleSlide = pres.addSlide();
titleSlide.background = { color: DARK_BG };

// Large title
titleSlide.addText(input.title, {
  x: 0.8, y: 1.6, w: 8.4, h: 1.6,
  fontSize: 40, bold: true, color: WHITE,
  fontFace: "Cambria", align: "left", valign: "middle", margin: 0,
});

// Subtitle
titleSlide.addText("Generated from document analysis", {
  x: 0.8, y: 3.4, w: 8.4, h: 0.6,
  fontSize: 16, color: ACCENT, fontFace: "Calibri", align: "left", margin: 0,
});

// Decorative oval accent
titleSlide.addShape(pres.shapes.OVAL, {
  x: 8.5, y: -0.8, w: 3.5, h: 3.5,
  fill: { color: ACCENT, transparency: 85 },
  line: { color: ACCENT, transparency: 85 },
});

// ── CONTENT SLIDES ───────────────────────────────────────────────────────────
input.slides.forEach((slide, idx) => {
  const s = pres.addSlide();
  s.background = { color: LIGHT_BG };

  // Slide number pill (top right)
  s.addShape(pres.shapes.ROUNDED_RECTANGLE, {
    x: 9.1, y: 0.2, w: 0.6, h: 0.35,
    fill: { color: DARK_BG }, rectRadius: 0.08,
    line: { color: DARK_BG },
  });
  s.addText(`${idx + 1}`, {
    x: 9.1, y: 0.2, w: 0.6, h: 0.35,
    fontSize: 11, color: WHITE, align: "center", valign: "middle",
    fontFace: "Calibri", margin: 0,
  });

  // Heading
  s.addText(slide.heading, {
    x: 0.5, y: 0.25, w: 8.4, h: 0.7,
    fontSize: 26, bold: true, color: DARK_BG,
    fontFace: "Cambria", align: "left", valign: "middle", margin: 0,
  });

  // Thin separator line (using a very flat rectangle — not an accent stripe)
  s.addShape(pres.shapes.RECTANGLE, {
    x: 0.5, y: 1.05, w: 8.9, h: 0.03,
    fill: { color: ACCENT }, line: { color: ACCENT },
  });

  // Bullets
  if (slide.bullets && slide.bullets.length > 0) {
    const bulletItems = slide.bullets.map((b, i) => ({
      text: b,
      options: {
        bullet: true,
        breakLine: i < slide.bullets.length - 1,
        fontSize: 15,
        color: BODY_COL,
        fontFace: "Calibri",
        paraSpaceAfter: 6,
      },
    }));

    s.addText(bulletItems, {
      x: 0.5, y: 1.2, w: 8.9, h: 4.0,
      valign: "top",
    });
  }

  // Speaker note
  if (slide.note) {
    s.addNotes(slide.note);
  }
});

// ── CLOSING SLIDE ─────────────────────────────────────────────────────────────
const closing = pres.addSlide();
closing.background = { color: DARK_BG };
closing.addText("Thank you", {
  x: 0.8, y: 2.0, w: 8.4, h: 1.2,
  fontSize: 40, bold: true, color: WHITE,
  fontFace: "Cambria", align: "left", margin: 0,
});
closing.addText("Generated by RAG Chat", {
  x: 0.8, y: 3.3, w: 8.4, h: 0.5,
  fontSize: 14, color: ACCENT, fontFace: "Calibri", align: "left", margin: 0,
});

pres.writeFile({ fileName: outputPath })
  .then(() => { console.log("OK:" + outputPath); process.exit(0); })
  .catch(err => { console.error("ERR:" + err.message); process.exit(1); });
